# Generated by Django 4.2.1 on 2023-06-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="Ricetta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immagine", models.ImageField(upload_to="")),
                ("nome", models.CharField(max_length=30)),
                ("ingredienti", models.CharField(max_length=500)),
                ("difficoltà", models.IntegerField(default=1)),
                ("tempo", models.IntegerField(default=1)),
                ("descrizione", models.CharField(max_length=1000)),
                (
                    "categoria",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ricette.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=35)),
                ("email", models.CharField(max_length=35)),
                ("password", models.CharField(max_length=8)),
                ("preferiti", models.ManyToManyField(to="ricette.ricetta")),
            ],
        ),
    ]
