# Generated by Django 4.2.1 on 2023-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ricette", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utente",
            name="preferiti",
            field=models.ManyToManyField(null=True, to="ricette.ricetta"),
        ),
    ]
