# Generated by Django 4.2.1 on 2023-06-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ricette", "0003_alter_utente_preferiti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="categoria",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
