# Generated by Django 4.2.1 on 2023-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ricette", "0004_alter_ricetta_categoria_delete_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="descrizione",
            field=models.CharField(max_length=50000),
        ),
    ]
