# Generated by Django 4.2.1 on 2023-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ricette", "0005_alter_ricetta_descrizione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="ingredienti",
            field=models.CharField(max_length=2000),
        ),
    ]
